#if NET8_0_OR_GREATER
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.DependencyInjection;

namespace Wolfgang.AuditTrail.Schema;



/// <summary>
/// Installs or upgrades the audit schema (<c>AuditHeader</c>,
/// <c>AuditDetail</c>, and <c>__AuditSchemaVersion</c>) in the target database.
/// Provider-agnostic: the DDL is generated by EF Core's own
/// <see cref="IMigrationsSqlGenerator"/>, supplied by whichever provider
/// (<c>UseSqlServer</c>, <c>UseNpgsql</c>, <c>UseMySql</c>, <c>UseSqlite</c>)
/// was wired up on the <see cref="AuditMigrationsDbContext"/>.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Fresh database.</strong> Nothing is installed, so the current model
/// is diffed against an empty one. EF Core produces <c>CreateTable</c> /
/// <c>CreateIndex</c> / <c>AddForeignKey</c> operations that the provider SQL
/// generator turns into provider-appropriate DDL. The result is the current
/// shape directly; earlier versions are never materialised and replayed.
/// </para>
/// <para>
/// <strong>Existing database behind the current version.</strong> The
/// create-from-empty diff would emit <c>CREATE TABLE</c> for tables that already
/// exist, so it is not used. Instead the explicit per-version steps in
/// <see cref="AuditSchemaUpgrades"/> are chained from the installed version up
/// to the current one and handed to the same SQL generator.
/// </para>
/// <para>
/// <strong>Already current.</strong> A no-op; no SQL is executed.
/// </para>
/// <para>
/// <strong>Ahead of the current version.</strong> Throws. A database written by
/// a newer build of this library cannot be safely downgraded, and silently
/// doing nothing would leave the application reading a shape it does not
/// understand.
/// </para>
/// <para>
/// The whole migration, every command plus the version-row update, runs in one
/// transaction, so a failure part-way leaves the recorded version unchanged.
/// </para>
/// <para>
/// <strong>Providers that implicitly commit DDL (MySQL and MariaDB) cannot
/// honour that guarantee.</strong> There, a failed upgrade can leave some
/// operations persisted while the version row still reads the old value, and
/// re-running does not recover: the migrator replays the whole step from the
/// old version, and the operations are not idempotent, so a replayed
/// <c>ADD COLUMN</c> fails on the column that already exists. Recovery on those
/// providers is manual: reconcile the tables against the target shape, then set
/// the version row by hand. This path has no integration coverage either, since
/// Pomelo caps at EF Core 9.x while the test project is on EF Core 10.
/// </para>
/// </remarks>
public static class AuditSchemaMigrator
{
    /// <summary>
    /// Applies any pending audit-schema migrations to the database backing
    /// <paramref name="context"/>.
    /// </summary>
    /// <param name="context">Migrations context configured for the target provider.</param>
    /// <param name="dryRun">When <c>true</c>, returns the SQL without executing.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// The SQL that would be executed when <paramref name="dryRun"/> is
    /// <c>true</c>; <see cref="string.Empty"/> otherwise, and also when the
    /// schema is already current and there is nothing to do.
    /// </returns>
    /// <exception cref="ArgumentNullException">If <paramref name="context"/> is <c>null</c>.</exception>
    /// <exception cref="InvalidOperationException">
    /// If the database records a schema version newer than this build installs.
    /// </exception>
    /// <exception cref="NotSupportedException">
    /// If the database records a version for which this build defines no upgrade
    /// step, which is a build gap rather than a configuration error.
    /// </exception>
    public static Task<string> RunAsync
    (
        AuditMigrationsDbContext context,
        bool dryRun = false,
        CancellationToken cancellationToken = default
    )
    {
        return RunAsync(context, AuditSchemaUpgrades.Instance, dryRun, cancellationToken);
    }



    /// <summary>
    /// Test seam. Identical to the public overload except that the version
    /// sequence is supplied rather than taken from
    /// <see cref="AuditSchemaUpgrades.Instance"/>, so the upgrade machinery can
    /// be driven end-to-end before a second production schema version exists.
    /// </summary>
    /// <exception cref="ArgumentNullException">
    /// If <paramref name="context"/> or <paramref name="upgrades"/> is <c>null</c>.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// If the database records a schema version newer than <paramref name="upgrades"/> installs.
    /// </exception>
    /// <exception cref="NotSupportedException">
    /// If <paramref name="upgrades"/> defines no step for the installed version.
    /// </exception>
    internal static async Task<string> RunAsync
    (
        AuditMigrationsDbContext context,
        IAuditSchemaUpgrades upgrades,
        bool dryRun,
        CancellationToken cancellationToken
    )
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(upgrades);

        var targetVersion = upgrades.CurrentVersion;

        var installedVersion = await AuditSchemaVersionStore
            .ReadInstalledVersionAsync(context, cancellationToken)
            .ConfigureAwait(false);

        if (installedVersion == targetVersion)
        {
            return string.Empty;
        }

        if (installedVersion > targetVersion)
        {
            throw new InvalidOperationException
            (
                $"The audit schema in this database is at version {installedVersion}, but this " +
                $"build installs version {targetVersion}. Downgrading the audit schema is not " +
                "supported. Run this application against a build that knows version " +
                $"{installedVersion}.");
        }

        var commands = installedVersion == 0
            ? GenerateInstallCommands(context)
            : GenerateUpgradeCommands(context, upgrades, installedVersion, targetVersion);

        if (dryRun)
        {
            return string.Join(";\n\n", commands.Select(c => c.CommandText));
        }

        await ApplyCommandsAsync(context, commands, targetVersion, cancellationToken).ConfigureAwait(false);
        return string.Empty;
    }



    /// <summary>
    /// Fresh install: diff the current model against nothing.
    /// </summary>
    private static IReadOnlyList<MigrationCommand> GenerateInstallCommands(AuditMigrationsDbContext context)
    {
        var differ       = context.GetService<IMigrationsModelDiffer>();
        var sqlGenerator = context.GetService<IMigrationsSqlGenerator>();
        var targetModel  = GetDesignTimeModel(context);

        var operations = differ.GetDifferences(
            source: null,
            target: targetModel.GetRelationalModel());

        return sqlGenerator.Generate(operations, targetModel);
    }



    /// <summary>
    /// Upgrade: chain one explicit step per version from
    /// <paramref name="installedVersion"/> up to <paramref name="targetVersion"/>.
    /// </summary>
    /// <remarks>
    /// Each step is generated separately so the emitted SQL follows the version
    /// order rather than whatever order a combined batch would produce. Every
    /// step is generated against the <em>current</em> model, which is safe
    /// precisely because the operations are explicit: an intermediate step says
    /// what it does rather than inferring it from a model it predates.
    /// </remarks>
    private static IReadOnlyList<MigrationCommand> GenerateUpgradeCommands
    (
        AuditMigrationsDbContext context,
        IAuditSchemaUpgrades upgrades,
        int installedVersion,
        int targetVersion
    )
    {
        var sqlGenerator   = context.GetService<IMigrationsSqlGenerator>();
        var targetModel    = GetDesignTimeModel(context);
        var upgradeContext = AuditSchemaUpgradeContext.FromModel(targetModel);

        var commands = new List<MigrationCommand>();

        for (var fromVersion = installedVersion; fromVersion < targetVersion; fromVersion++)
        {
            var operations = upgrades.StepFrom(fromVersion, upgradeContext);
            commands.AddRange(sqlGenerator.Generate(operations, targetModel));
        }

        return commands;
    }



    /// <summary>
    /// EF Core 7+ split the runtime and design-time models. Migrations need the
    /// design-time model, which retains the relational annotations the differ
    /// and the SQL generator inspect.
    /// </summary>
    private static IModel GetDesignTimeModel(AuditMigrationsDbContext context)
    {
        return context.GetService<IDesignTimeModel>().Model;
    }



    private static Task ApplyCommandsAsync
    (
        AuditMigrationsDbContext context,
        IReadOnlyList<MigrationCommand> commands,
        int targetVersion,
        CancellationToken cancellationToken
    )
    {
        // Route through IExecutionStrategy so this composes with SQL Server's
        // EnableRetryOnFailure (or any other retrying strategy). Directly
        // calling BeginTransactionAsync on a context configured with a retrying
        // strategy throws. EF Core requires the whole transactional operation
        // to be wrapped so the strategy can re-run it on transient failures.
        var strategy = context.Database.CreateExecutionStrategy();
        return strategy.ExecuteAsync(
            (Context: context, Commands: commands, TargetVersion: targetVersion),
            static async (_, state, ct) =>
            {
                await state.Context.Database.OpenConnectionAsync(ct).ConfigureAwait(false);
                try
                {
                    // MA0004: see the matching note in DbContextAuditSchemaExtensions.
                    // `await using var` cannot ConfigureAwait the implicit DisposeAsync.
                    var transaction = await state.Context.Database
                        .BeginTransactionAsync(ct)
                        .ConfigureAwait(false);
                    await using var configuredTx = transaction.ConfigureAwait(false);

                    foreach (var command in state.Commands)
                    {
#pragma warning disable EF1002 // SQL is generated by EF Core's own SqlGenerator; not user input.
                        await state.Context.Database
                            .ExecuteSqlRawAsync(command.CommandText, ct)
                            .ConfigureAwait(false);
#pragma warning restore EF1002
                    }

                    await AuditSchemaVersionStore
                        .UpsertInstalledVersionAsync(state.Context, state.TargetVersion, ct)
                        .ConfigureAwait(false);

                    await transaction.CommitAsync(ct).ConfigureAwait(false);
                }
                finally
                {
                    await state.Context.Database.CloseConnectionAsync().ConfigureAwait(false);
                }

                return 0; // ExecuteAsync<TState, TResult> needs a return value; the migrator is fire-and-forget.
            },
            verifySucceeded: null,
            cancellationToken: cancellationToken);
    }
}
#endif
